### ISSUE TITLE
Switch default branch to rails-rewrite 

### ISSUE THREAD

**Issue by snowe2010** [ColoradoSchoolOfMines/schedule_miner#11]
I think we should switch the default branch to the rails-rewrite branch. 
Several reasons:
- pull requests and code commits are set against the default branch
- contributions will show up in our graph 
- we can close issues through commits
- the master branch is stable and we aren't really developing further. Therefore it shouldn't be the first thing visitors see

**Comment by pianohacker** [comment]
+1.

**Comment by pianohacker** [comment]
As we have moved the old contents to v1.0, and rails-rewrite to master, this is done.
