### ISSUE TITLE
Implement a system to read Trailhead courses into the database

### ISSUE THREAD

**Issue by snowe2010** [ColoradoSchoolOfMines/schedule_miner#12]
We need to implement some sort of system to read course info from Trailhead into the database for SM. 

There are several ways we could accomplish this:
- Copy the html the same way it is currently used by SM (PHP)
- Gain access through some Trailhead API (extremely unlikely to happen)
- Access the course info from another location, maybe from where it is before it is put into Trailhead.

I'm unsure of where to go from here. If we could design a system that could read in the data from an HTML file for now and make it modular enough to be able to switch over to an API to Trailhead or the actual location of the schedules at a later time that would be best.

**Comment by snowe2010** [comment]
Sweet so it turns out that Mines has a Trailhead site open to the public, no login required. I'm going to begin implementing a system to automatically pull the schedule from this system. 

https://banner.mines.edu/prod/owa/bwckschd.p_disp_dyn_sched

Since we can read stuff in this way, should we implement reading the data from each actual "Subject" in Trailhead? For example, read from Air Force and put it into an Air Force section on SM?

**Comment by pianohacker** [comment]
Martin said Wednesday he was working on a way to get us more straightforward and simple access (less HTML scraping, more actual data import in a CSV or something). This might be useful as a backup plan, but there's a chance we won't have to go through this pain.

**Comment by snowe2010** [comment]
Hmm. Darn wish I had read this a few hours ago. I'm almost done. HTML scraping isn't bad with Nokogiri though.

**Comment by snowe2010** [comment]
It would most definitely be faster to load it in a csv or some sort of nicer format. The html output from _just the table of classes_ is more than 90k lines of html.

**Comment by snowe2010** [comment]
So I finished the script to pull courses, but I don't know how we should implement it with the database. Any thoughts?

**Comment by pianohacker** [comment]
This has been extended to add the relevant data to the database. Closing.
