### ISSUE TITLE
Difficult to remove classes from schedule

### ISSUE THREAD

**Issue by lwalen** [ColoradoSchoolOfMines/schedule_miner#2]
#### Issue

Currently, one must determine the CRN of the class they wish to remove by looking at their schedule. Next they must locate that CRN in the course sections field. Then they must select and delete that CRN. Then they must click 'Save Sections'. This is cumbersome and prone to error.
#### Proposal

Add a delete button to either the class tile in the calendar, or to its box to the right of the calendar, or both.

**Comment by pianohacker** [comment]
Sounds like a good idea, thanks for entering it in.

**Comment by snowe2010** [comment]
I think this would be good to get in by the time registration happens. Could you figure it out Jesse?

**Comment by pianohacker** [comment]
At this point, we are focusing all of our development efforts on the rewrite. Thanks much for the suggestion, though, we'll make sure this is in the new version.
