### ISSUE TITLE
Photos broken in vpn doco

### ISSUE THREAD

**Issue by ybakos** [ColoradoSchoolOfMines/schedule_miner#7]
When viewing https://github.com/ColoradoSchoolOfMines/schedule_miner/wiki/Accessing-the-site-from-off-Campus
It seems the photo urls are no longer valid.

Thanks @muff1nman for creating the doc -- perhaps adding a doc/images directory to the repo, storing the images there, and referencing them in the wiki page's markdown.

**Comment by muff1nman** [comment]
Should be fixed now.  Images were uploaded to doc/images and referenced accordingly.
