### ISSUE TITLE
Not setup to use Spring 2014 classes

### ISSUE THREAD

**Issue by sgonzalez** [ColoradoSchoolOfMines/schedule_miner#9]
Schedule Miner is still using the Fall 2013 classes. I would like to use it for next semester but I cannot due to this issue.

It should be a quick fix, I imagine.

**Comment by pianohacker** [comment]
Working on fixing it.

**Comment by pianohacker** [comment]
Okay, they're in. Trailhead's changed its format for no good reason. The import tool now has a 6 in it instead of a 0. So much rage.
